### ISSUE TITLE
[BUG] - Declaration of Maxbanton\Cwh\Handler\CloudWatch::write(array $record)...

### ISSUE THREAD

**Issue by slps970093** [tarfin-labs/laravel-cloudwatch-logger#7]
Describe the bug
Declaration of Maxbanton\Cwh\Handler\CloudWatch::write(array $record): void must be compatible with Monolog\Handler\AbstractProcessingHandler::write(Monolog\LogRecord $record): void

PHP Version: 8.2x
Laravel : 10x

**Comment by tkaratug** [comment]
Hi @slps970093,

Just wanted to let you know that the issue you reported has been resolved and closed with the recent release ([2.5.0](https://github.com/tarfin-labs/laravel-cloudwatch-logger/releases/tag/v2.5.0)). Your contribution was instrumental in fixing this. Thanks for raising it!

Best regards,
Turan.
